import { desc,eq,sql } from "drizzle-orm"; import { drizzle } from "drizzle-orm/mysql2"; import { chatMessages,conversations,InsertUser,users,waitlist } from "../drizzle/schema"; import { ENV } from "./_core/env";
let _db:ReturnType<typeof drizzle>|null=null; export async function getDb(){if(!_db&&process.env.DATABASE_URL){try{_db=drizzle(process.env.DATABASE_URL)}catch(e){console.warn("[Database] Failed to connect",e)}}return _db}
export async function upsertUser(user:InsertUser){const db=await getDb();if(!db)return;const values:InsertUser={openId:user.openId,name:user.name??null,email:user.email??null,loginMethod:user.loginMethod??null,lastSignedIn:new Date()};if(user.openId===ENV.ownerOpenId)values.role="admin";await db.insert(users).values(values).onDuplicateKeyUpdate({set:{name:values.name,email:values.email,lastSignedIn:values.lastSignedIn}})}
export async function getUserByOpenId(openId:string){const db=await getDb();if(!db)return;const r=await db.select().from(users).where(eq(users.openId,openId)).limit(1);return r[0]}
export async function addWaitlistEmail(email:string,source="homepage"){const db=await getDb();if(!db)return {email,source};await db.insert(waitlist).values({email,source});return (await db.select().from(waitlist).where(eq(waitlist.email,email)).limit(1))[0]}
export async function countWaitlist(){const db=await getDb();if(!db)return 0;const r=await db.select({count:sql<number>`count(*)`}).from(waitlist);return Number(r[0]?.count??0)}
export async function createConversation(userId:number,title:string,model:string){const db=await getDb();if(!db)return {id:Date.now(),userId,title,model};const r=await db.insert(conversations).values({userId,title,model});return {id:Number(r[0].insertId),userId,title,model}}
export async function listConversations(userId:number){const db=await getDb();if(!db)return [];return db.select().from(conversations).where(eq(conversations.userId,userId)).orderBy(desc(conversations.updatedAt))}
export async function getConversationMessages(conversationId:number){const db=await getDb();if(!db)return [];return db.select().from(chatMessages).where(eq(chatMessages.conversationId,conversationId)).orderBy(chatMessages.createdAt)}
export async function addChatMessage(conversationId:number,role:"user"|"assistant"|"system",content:string,model?:string){const db=await getDb();if(db)await db.insert(chatMessages).values({conversationId,role,content,model});return {conversationId,role,content,model}}
